PlebeianTech/plebeian-market

- web/src/lib/components/Auction.svelte
- web/src/lib/components/AuctionEndMessage.svelte
- web/src/lib/components/Handshake.svelte
- web/src/lib/components/QR.svelte
Phrasing, margins, small adjustments
> Small adjustments to front end

- web/src/routes/about.svelte
> Increase content width on about page.

- web/package-lock.json
- web/package.json
- web/src/app.css
- web/src/routes/index.svelte
Rough draft, needs work, however it should be the right idea to close #11 
See [video](https://www.loom.com/share/c5e2af58120140cf92b27d4653808f77)
> Rough draft of changes to home page for issue #11

- web/src/routes/index.svelte
Center text, reduce spacing, and remove shaded background for typewriter element.
> hr-20220615-03

- web/src/routes/about.svelte
> Make text bigger and more space between paragraphs.

- web/src/lib/components/Auction.svelte
- web/src/lib/components/Carousel.svelte
- web/src/lib/components/Footer.svelte
- web/src/routes/index.svelte
This should resolve the issue with space above and below carousel, the issue with footer floating in the middle of mobile screen on duckduckgo browser, and the issue with text overlapping onto the graphics on the home page.
> Hr 20220621 04

- web/src/lib/components/PublicAuctionCard.svelte
- web/src/lib/services/api.ts
- web/src/lib/types/user.ts
Show button on PublicAuctionCard.
> Button for moderator to unfeature auctions.

- web/src/lib/components/AuctionEditor.svelte
removes the cheat sheet and fixes the markdown
> remove cheat sheet and fix markdown

- web/src/app.css
- web/src/lib/components/MarkdownDescriptionEditor.svelte
Markdown Editor Component
5 Buttons
- Header Two
- Header Three
- Bold
- Italic
- List Item
(No underline - its not a markdown thing its a css thing)
Also updates links in the markdown to be daisy pink
> add buttons for markdown editor

- api/api.py
- api/api_tests.py
fix broken unit tests, add new unit tests for users auctions, fix bugs found in getting users auctions
> fix unit tests and fetch auctions

- docker-compose.prod.yml
- docker-compose.staging.yml
- web/.env.development
- web/.env.production
- web/.env.staging
- web/Dockerfile
- web/package.json
- web/src/lib/components/AuctionEditor.svelte
- web/src/lib/components/Login.svelte
- web/src/lib/components/Navbar.svelte
- web/src/lib/services/api.ts
- web/src/lib/types/auction.ts
- web/src/lib/utils.ts
Using environment files to store variables. Also, change Local for Development so it matches the official names of the environments
> Using environment files to store variables

- web/src/lib/components/StallView.svelte
Moved the avatars below the hero section and added 3-col mobile
> Jay 20230105 campaign avatars fix

- web/.env
- web/src/lib/components/ItemView.svelte
- web/src/lib/types/auction.ts
- web/src/lib/types/campaign.ts
- web/src/lib/types/item.ts
- web/src/lib/types/listing.ts
- web/src/lib/types/user.ts
- web/src/lib/utils.ts
- web/src/routes/+page.svelte
- web/src/routes/campaigns/[...key]/+page.svelte
- web/src/routes/stall/[nym]/+page.svelte
Better solution to put limits to opengraph tags so twitter can parse and display them
> Better solution to put limits to opengraph tags

- web/package-lock.json
- web/package.json
- web/src/lib/components/NostrChat.svelte
- web/src/lib/components/StallView.svelte
- web/src/lib/nostr/pool.ts
- web/src/lib/nostr/utils.js
- web/src/routes/marketsquare/+page.svelte
- It's currently enabled for all environments but Production.
- Stalls are "per-environment", so everyone can experiment in `dev` or `staging` without poluting `Prod` stall.
- It must be used WITH a nostr extension. Code to use PM created identify incoming.
- `Market Square` channel is currently the "Nostr" nostr channel, not PM one, so we can see messages loading there. We'll create and add the PM channel soon (TM).
> Alpha version of Plebeian Market Nostr code

- web/src/lib/components/NostrChat.svelte
- web/src/lib/components/NostrNote.svelte
- web/src/lib/nostr/utils.js
Full back-end support + basic UI
> Nostr nip05 support

- web/src/lib/components/nostr/Chat.svelte
- web/src/lib/components/nostr/Note.svelte
- web/src/lib/components/nostr/NoteActions.svelte
- web/src/lib/nostr/pool.ts
- web/src/lib/nostr/utils.js
- web/tailwind.config.cjs
- Timers were running forever, so each page change to a Nostr page was running a lot of timers. Now we keep track of them and stop them onDestroy
- Now you can see the message that another message is replying to.
- Nostr Media cache is disabled again, as it's not pulling some profile pictures (needs further investigation).
IU/UX is provisional, as always.
> Nostr show replies in chat

- web/src/lib/components/nostr/Button.svelte
- web/src/lib/components/nostr/Chat.svelte
- web/src/lib/components/nostr/NoteActions.svelte
- web/src/lib/nostr/pool.ts
Now the Nostr actions that need a private key are enabled only if you have a Nostr extension or you're logged-in into Plebeian Market.
> Nostr improve login situation

- web/src/lib/components/nostr/Chat.svelte
Fix problem with nostr extension toggle not updating because it's still not present until afterwards.
Show the toggle always (like before), and clarify when user don't have extension in a tooltip.
> Fix problem with nostr extension toggle

- web/.env
- web/.env.production
- web/package-lock.json
- web/package.json
- web/src/lib/components/nostr/Button.svelte
- web/src/lib/nostr/pool.ts
- web/src/lib/nostr/utils.js
- web/src/routes/marketsquare/+page.svelte
And update nostr-tools to last version
> Nostr move market square channel ID to config files

- web/frontoffice/package-lock.json
- web/frontoffice/package.json
- web/frontoffice/src/lib/components/settings/SetupHomepage.svelte
- web/frontoffice/src/lib/components/stores/Browse.svelte
- web/frontoffice/src/lib/components/stores/ProductCardBrowser.svelte
- web/frontoffice/src/lib/components/stores/ProductList.svelte
- web/frontoffice/src/lib/utils.ts
- web/frontoffice/src/routes/+layout.svelte
- web/frontoffice/src/routes/+page.svelte
- web/frontoffice/src/routes/product/[product_id]/+page.svelte
> Frontstore fixes when config.json is not present

- web/backoffice/src/lib/components/settings/Wallet.svelte
- web/frontoffice/src/routes/p/[pubkey]/+page.svelte
- web/shared/src/lib/components/FaqInfo.svelte
This also closes "other badges" by default, letting the users open it manually.
> FAQ about How to get badges

- api/lnd_hub_client.py
Hey guys, Adithya from [Alby](https://getalby.com/) here!
We recently updated our ln address proxy link to be on api.getalby.com (https://github.com/getAlby/lightning-address-details-proxy/pull/12) so I thought of updating it here as well.
> update lnaddress proxy url

- api/Dockerfile
- birdwatcher/Dockerfile
- ln_payments_processor/Dockerfile
- services/nginx/Dockerfile
Using "slim" containers where possible to save on disk space and speed up installation.
> Using newer smaller containers

- web/frontoffice/src/lib/components/nostr/ShowExternalIdentities.svelte
- web/frontoffice/src/lib/components/settings/ExternalIdentities.svelte
- web/frontoffice/src/routes/p/[pubkey]/+page.svelte
> Add nip-05 verification checkmark in the Private Messages view

- web/frontoffice/src/lib/components/nostr/BadgeModal.svelte
- web/frontoffice/src/routes/p/[pubkey]/+page.svelte
> Only show "Accept badge" button when viewing my own unaccepted badges

- api/main.py
- web/shared/src/lib/components/Navbar.svelte
- web/shared/src/lib/components/nostr/PrivateMessages.svelte
Show Order ID in invoices + Navbar improvements for low/medium screen resolutions
> Show Order ID in invoices + Navbar improvements

- web/backoffice/src/lib/components/StallView.svelte
- web/frontoffice/package-lock.json
- web/frontoffice/package.json
- web/frontoffice/src/lib/components/stores/ShippingOptions.svelte
- web/frontoffice/src/lib/components/stores/ShoppingCart.svelte
- web/shared/src/lib/currencies.ts
Advanced shipping options having into account the stall shipping costs and the products shipping costs
> Advanced shipping options

- web/frontoffice/package-lock.json
- web/frontoffice/package.json
- web/frontoffice/src/lib/components/stores/BidList.svelte
- web/frontoffice/src/lib/components/stores/BidWidget.svelte
- web/frontoffice/src/lib/components/stores/Product.svelte
- web/shared/package-lock.json
- web/shared/package.json
We'll show unaccepted bids only to admins and to the bidder himself, so he knows what's happening.
> Hide unaccepted bids
